create table fips (
	id int unsigned not null auto_increment primary key,
	`code` char(4) not null,
	`name` varchar(255) not null,
	`fip_type_id` int unsigned not null
);

create table fip_types (
	id int unsigned not null auto_increment primary key,
	`name` varchar(255) not null
);

insert into fip_types value
(NULL, 'province'),(NULL, 'city');

insert into fips values
(NULL, 'RP01', 'Abra', 1),
(NULL, 'RP02', 'Agusan del Norte', 1),
(NULL, 'RP03', 'Agusan del Sur', 1),
(NULL, 'RP04', 'Aklan', 1),
(NULL, 'RPH4', 'Alaminos', 2),
(NULL, 'RP05', 'Albay', 1),
(NULL, 'RPA1', 'Angeles', 2),
(NULL, 'RPH5', 'Antipolo', 2),
(NULL, 'RP06', 'Antique', 1),
(NULL, 'RPH6', 'Apayao', 1),
(NULL, 'RPG8', 'Aurora', 1),
(NULL, 'RPA2', 'Bacolod', 2),
(NULL, 'RPA3', 'Bago', 2),
(NULL, 'RPA4', 'Baguio', 2),
(NULL, 'RPA5', 'Bais', 2),
(NULL, 'RPH7', 'Balanga', 2),
(NULL, 'RP22', 'Basilan', 1),
(NULL, 'RPA6', 'Basilan', 2),
(NULL, 'RP07', 'Bataan', 1),
(NULL, 'RP08', 'Batanes', 1),
(NULL, 'RP09', 'Batangas', 1),
(NULL, 'RPA7', 'Batangas', 2),
(NULL, 'RPH8', 'Bayawan', 2),
(NULL, 'RP10', 'Benguet', 1),
(NULL, 'RPH9', 'Biliran', 1),
(NULL, 'RPI1', 'Bislig', 2),
(NULL, 'RP11', 'Bohol', 1),
(NULL, 'RP12', 'Bukidnon', 1),
(NULL, 'RP13', 'Bulacan', 1),
(NULL, 'RPA8', 'Butuan', 2),
(NULL, 'RPA9', 'Cabanatuan', 2),
(NULL, 'RPB1', 'Cadiz', 2),
(NULL, 'RP14', 'Cagayan', 1),
(NULL, 'RPB2', 'Cagayan de Oro', 2),
(NULL, 'RPI2', 'Calamba', 2),
(NULL, 'RPI3', 'Calapan', 2),
(NULL, 'RPB3', 'Calbayog', 2),
(NULL, 'RPB4', 'Caloocan', 2),
(NULL, 'RP15', 'Camarines Norte', 1),
(NULL, 'RP16', 'Camarines Sur', 1),
(NULL, 'RP17', 'Camiguin', 1),
(NULL, 'RPI4', 'Candon', 2),
(NULL, 'RPB5', 'Canlaon', 2),
(NULL, 'RP18', 'Capiz', 1),
(NULL, 'RP19', 'Catanduanes', 1),
(NULL, 'RPI5', 'Cauayan', 2),
(NULL, 'RP20', 'Cavite', 1),
(NULL, 'RPB6', 'Cavite', 2),
(NULL, 'RP21', 'Cebu', 1),
(NULL, 'RPB7', 'Cebu', 2),
(NULL, 'RPI6', 'Compostela Valley', 1),
(NULL, 'RPB8', 'Cotabato', 2),
(NULL, 'RP57', 'Cotabato', 1),
(NULL, 'RPB9', 'Dagupan', 2),
(NULL, 'RPC1', 'Danao', 2),
(NULL, 'RPC2', 'Dapitan', 2),
(NULL, 'RPC3', 'Davao', 2),
(NULL, 'RPI7', 'Davao del Norte', 1),
(NULL, 'RP25', 'Davao del Sur', 1),
(NULL, 'RP26', 'Davao Oriental', 1),
(NULL, 'RPI8', 'Digos', 2),
(NULL, 'RPI9', 'Dinagat Islands', 1),
(NULL, 'RPC4', 'Dipolog', 2),
(NULL, 'RPC5', 'Dumaguete', 2),
(NULL, 'RP23', 'Eastern Samar', 1),
(NULL, 'RPJ1', 'Escalante', 2),
(NULL, 'RPJ2', 'Gapan', 2),
(NULL, 'RPC6', 'General Santos', 2),
(NULL, 'RPC7', 'Gingoog', 2),
(NULL, 'RPJ3', 'Guimaras', 1),
(NULL, 'RPJ4', 'Himamaylan', 2),
(NULL, 'RP27', 'Ifugao', 1),
(NULL, 'RPC8', 'Iligan', 2),
(NULL, 'RP28', 'Ilocos Norte', 1),
(NULL, 'RP29', 'Ilocos Sur', 1),
(NULL, 'RP30', 'Iloilo', 1),
(NULL, 'RPC9', 'Iloilo', 2),
(NULL, 'RPD1', 'Iriga', 2),
(NULL, 'RP31', 'Isabela', 1),
(NULL, 'RPJ5', 'Isabela', 2),
(NULL, 'RPJ6', 'Kabankalan', 2),
(NULL, 'RPJ7', 'Kalinga', 1),
(NULL, 'RPJ8', 'Kidapawan', 2),
(NULL, 'RPJ9', 'Koronadal', 2),
(NULL, 'RPD2', 'La Carlota', 2),
(NULL, 'RP33', 'Laguna', 1),
(NULL, 'RP34', 'Lanao del Norte', 1),
(NULL, 'RP35', 'Lanao del Sur', 1),
(NULL, 'RPD3', 'Laoag', 2),
(NULL, 'RPD4', 'Lapu-Lapu', 2),
(NULL, 'RPK1', 'Las Piñas', 2),
(NULL, 'RP36', 'La Union', 1),
(NULL, 'RPD5', 'Legaspi', 2),
(NULL, 'RP37', 'Leyte', 1),
(NULL, 'RPK2', 'Ligao', 2),
(NULL, 'RPD6', 'Lipa', 2),
(NULL, 'RPD7', 'Lucena', 2),
(NULL, 'RPK3', 'Maasin', 2),
(NULL, 'RP56', 'Maguindanao', 1),
(NULL, 'RPK4', 'Makati', 2),
(NULL, 'RPK5', 'Malabon', 2),
(NULL, 'RPK6', 'Malaybalay', 2),
(NULL, 'RPK7', 'Malolos', 2),
(NULL, 'RPK8', 'Mandaluyong', 2),
(NULL, 'RPD8', 'Mandaue', 2),
(NULL, 'RPD9', 'Manila', 2),
(NULL, 'RPE1', 'Marawi', 2),
(NULL, 'RPK9', 'Marikina', 2),
(NULL, 'RP38', 'Marinduque', 1),
(NULL, 'RP39', 'Masbate', 1),
(NULL, 'RPL1', 'Masbate', 2),
(NULL, 'RPL2', 'Meycauayan', 2),
(NULL, 'RP40', 'Mindoro Occidental', 1),
(NULL, 'RP41', 'Mindoro Oriental', 1),
(NULL, 'RP42', 'Misamis Occidental', 1),
(NULL, 'RP43', 'Misamis Oriental', 1),
(NULL, 'RP44', 'Mountain', 1),
(NULL, 'RPL3', 'Muñoz', 2),
(NULL, 'RPL4', 'Muntinlupa', 2),
(NULL, 'RPE2', 'Naga', 2),
(NULL, 'RPL5', 'Navotas', 2),
(NULL, 'RPH3', 'Negros Occidental', 1),
(NULL, 'RP46', 'Negros Oriental', 1),
(NULL, 'RP67', 'Northern Samar', 1),
(NULL, 'RP47', 'Nueva Ecija', 1),
(NULL, 'RP48', 'Nueva Vizcaya', 1),
(NULL, 'RP40', 'Occidental Mindoro', 1),
(NULL, 'RPE3', 'Olongapo', 2),
(NULL, 'RP41', 'Oriental Mindoro', 1),
(NULL, 'RPE4', 'Ormoc', 2),
(NULL, 'RPE5', 'Oroquieta', 2),
(NULL, 'RPE6', 'Ozamis', 2),
(NULL, 'RPE7', 'Pagadian', 2),
(NULL, 'RP49', 'Palawan', 1),
(NULL, 'RPE8', 'Palayan', 2),
(NULL, 'RP50', 'Pampanga', 1),
(NULL, 'RPL6', 'Panabo', 2),
(NULL, 'RP51', 'Pangasinan', 1),
(NULL, 'RPL7', 'Parañaque', 2),
(NULL, 'RPE9', 'Pasay', 2),
(NULL, 'RPL8', 'Pasig', 2),
(NULL, 'RPL9', 'Passi', 2),
(NULL, 'RPF1', 'Puerto Princesa', 2),
(NULL, 'RPH2', 'Quezon', 1),
(NULL, 'RPF2', 'Quezon', 2),
(NULL, 'RP68', 'Quirino', 1),
(NULL, 'RP53', 'Rizal', 1),
(NULL, 'RP54', 'Romblon', 1),
(NULL, 'RPF3', 'Roxas', 2),
(NULL, 'RPM1', 'Sagay', 2),
(NULL, 'RPM2', 'Samal', 2),
(NULL, 'RP55', 'Samar', 1),
(NULL, 'RPF4', 'San Carlos (Negros Occidental)', 2),
(NULL, 'RPF5', 'San Carlos (Pangasinan)', 2),
(NULL, 'RPM3', 'San Fernando (La Union)', 2),
(NULL, 'RPM4', 'San Fernando (Pampanga)', 2),
(NULL, 'RPF6', 'San Jose', 2),
(NULL, 'RPM5', 'San Jose del Monte', 2),
(NULL, 'RPM6', 'San Juan', 2),
(NULL, 'RPF7', 'San Pablo', 2),
(NULL, 'RPM7', 'Santa Rosa', 2),
(NULL, 'RPM8', 'Santiago', 2),
(NULL, 'RPM9', 'Sarangani', 2),
(NULL, 'RPF8', 'Silay', 2),
(NULL, 'RPN1', 'Sipalay', 2),
(NULL, 'RP69', 'Siquijor', 1),
(NULL, 'RP58', 'Sorsogon', 1),
(NULL, 'RPN2', 'Sorsogon', 2),
(NULL, 'RP70', 'South Cotabato', 1),
(NULL, 'RP59', 'Southern Leyte', 1),
(NULL, 'RP71', 'Sultan Kudarat', 1),
(NULL, 'RP60', 'Sulu', 1),
(NULL, 'RPF9', 'Surigao', 2),
(NULL, 'RP61', 'Surigao del Norte', 1),
(NULL, 'RPN3', 'Surigao del Norte', 1),
(NULL, 'RP62', 'Surigao del Sur', 1),
(NULL, 'RPN4', 'Tabaco', 2),
(NULL, 'RPG1', 'Tacloban', 2),
(NULL, 'RPN5', 'Tacurong', 2),
(NULL, 'RPG2', 'Tagaytay', 2),
(NULL, 'RPG3', 'Tagbilaran', 2),
(NULL, 'RPN6', 'Taguig', 2),
(NULL, 'RPN7', 'Tagum', 2),
(NULL, 'RPN8', 'Talisay (Cebu)', 2),
(NULL, 'RPN9', 'Talisay (Negros Occidental)', 2),
(NULL, 'RPO1', 'Tanauan', 2),
(NULL, 'RPO2', 'Tangub', 2),
(NULL, 'RPG4', 'Tanjay', 2),
(NULL, 'RPO3', 'Tarlac', 1),
(NULL, 'RP63', 'Tarlac', 2),
(NULL, 'RPO4', 'Tawi-Tawi', 1),
(NULL, 'RP72', 'Toledo', 2),
(NULL, 'RPG5', 'Trece Martires', 2),
(NULL, 'RPG6', 'Tuguegarao', 2),
(NULL, 'RPO5', 'Urdaneta', 2),
(NULL, 'RPO6', 'Valencia', 2),
(NULL, 'RPO7', 'Valenzuela', 2),
(NULL, 'RPO8', 'Victorias', 2),
(NULL, 'RPO9', 'Vigan', 2),
(NULL, 'RPP1', 'Zambales', 1),
(NULL, 'RP64', 'Zamboanaga del Sur', 1),
(NULL, 'RPP2', 'Zamboanga', 2),
(NULL, 'RPG7', 'Zamboanga del Norte', 1),
(NULL, 'RP65', 'Zamboanga del Sur', 1),
(NULL, 'RP66', 'Zamboanga Sibugay', 1);
