Data.dmo: /Users/juliuslagutan/Desktop/dmo/
#Data.stations: /data/stations/
Data.readings: /Users/juliuslagutan/weather.com.ph/data/readings/

Tile.main.url: http://a.tiles.mapbox.com/v3/meteomedia.WeatherPH-Default