---
Comment.date_time_format: M d, Y
Comment.feed_limit: 10
Comment.level: 1
Hook.bootstraps: weatherph
#Meta.description: 'Croogo - A CakePHP powered Content Management System'
Meta.generator: 'Weather Philippines'
Meta.keywords: weather,Philippines, weather philippines, weather tv, dictionary, news, webcam, payong panahon, mata ng bagyo, typhoon, typhoon preparedness, typhoon climatology, pressure, satellite, temperature, meteomedia philippines, meteomedia, aboitiz power, union bank, weather movies
Meta.robots: index, follow
Reading.date_time_format: D, M d Y H:i:s
Reading.nodes_per_page: 5
Service.akismet_key: your-key
Service.akismet_url: http://your-blog.com
Service.recaptcha_private_key: 6LcD_toSAAAAAAjyz0vX25aiqpU6ij6CrdkZosSS
Service.recaptcha_public_key: 6LcD_toSAAAAALoNg2FHQgZCN0vPwCJAQ4ELSXSh
Site.email: sgauran@meteomedia.com.ph
Site.feed_url:
Site.locale: eng
Site.status: 1
Site.tagline: A CakePHP powered Content Management System.
Site.theme: weatherph
Site.timezone: 8
Site.title: Weather Philippines
Writing.wysiwyg: 1
Site.timezone: Asia/Manila
Data.dmo: /data/dmo/live/
Data.stations: /data/stations/
Data.readings: /data/readings/
Data.movies: http://weather.com.ph:7777/
Data.uploaded_videos: http://weather.com.ph:7777/
Data.uploaded_images_folder: /data/images/uploads/
Data.uploaded_images: /images/
Data.weathertv: http://weather.com.ph:7777/
Data.layers: /theme/weatherph/img/layers/
Server.node: http://weather.com.ph:7777/

Abfrage.username: wget
Abfrage.password: p09tM20

Tile.main.url:        http://a.tiles.mapbox.com/v3/meteomedia.map-a3uyawtu
Tile.temperature.url: http://{s}.tiles.mapbox.com/v3/meteomedia.WeatherPH-Temperature-2
Tile.pressure.url:    http://{s}.tiles.mapbox.com/v3/meteomedia.WeatherPH-Pressure

Tile.main.ext: png
# Tile.main.url: http://tile.stamen.com/toner
# Tile.main.ext: jpg
Tile.tiles: http://tiles.alpha.weather.com.ph
Tile.attr: Meteomedia, © OpenStreetMap & contributors, CC-BY-SA
